modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/sekelsta/horse-colors/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/realistic-horse-genetics"
    logoFile="logo.png"
    authors="${mod_authors}"
    credits="Thanks to faainleog for contributing some gorgeous textures! Thanks also to Rambonata and RosaNera for making textures, and to everyone who has translated the mod."
    description='''
"Blacks and bays, dapples and grays
Running in the night
When you wake, you shall have
All the pretty little ponies"

This mod adds biologically correct genetics for horses, massively expanding the available coat colors and patterns, as well as plausible genetics for speed, health, and jump height. Mendelian and non-Mendelian inheritance are used where applicable, including chromosome linkage based on published research.
'''

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

